### ISSUE TITLE
Trigger updates on sign in attempt

### ISSUE THREAD

**Issue by mpj** [discourse/discourse-patreon#8]
I'd like Discourse to update the status of the logged in user with the Patreon API upon login, not just in the batch script and the web hook. Otherwise, a user that creates their forum account after pledging on Patreon will have to wait up to 6 hours before their rewards kick in.

## Background
I have a forum that is essentially on complete lockdown until the user becomes a Patron - basically, a Patron-only forum. Thus, the users do NOT sign up for Discourse first, they become Patrons, and are then directed to the forum, where they log in with their Patreon account. On login, they won't have access because the account did not exist at the time of the webhook trigger, and the batch script that syncs (https://github.com/discourse/discourse-patreon/blob/master/app/jobs/scheduled/patreon_sync_patrons_to_groups.rb) only triggers every 6 hours.

**Comment by xfalcox** [comment]
Did you set webhooks as said in the guide? They make the Forum update the patron list on every new pledge, so this would not happen.

**Comment by mpj** [comment]
@xfalcox The webhooks are set up, but that's not relevant. I mention this above but I might have been unclear - it will not help that it updates on the pledge, because the webhook happens too early. The forum account does not exist at the time of pledging, because the user becomes a patron first, and only then it makes sense for the user to visit the forum, as it is closed and worthless before they are a patron. I.e. when the webhook happens, there is nothing for it to update.

**Comment by mpj** [comment]
I.e. the flow assumes that the Discourse forum is something that the user is already using at the time of becoming a Patron. In my case, the forum itself is a reward.

**Comment by mpj** [comment]
Thanks for you AMAZINGLY fast responses by the way, very impressive.

**Comment by xfalcox** [comment]
1. User becomes a patron
2. Discourse gets a webhooks, add this new email to the patron list internally
3. user creates a new forum account
4. This code [here](https://github.com/discourse/discourse-patreon/blob/master/plugin.rb#L100-L123) should find that he's already a patron and add him to all groups

We have a few customers using it this way, and it's working. If there is an exception on this flow, we even log it, so you can search for something there.

**Comment by mpj** [comment]
**Resolved!** It was my bad!!

While debugging https://github.com/discourse/discourse-patreon/issues/9 we created multiple clients on the Patreon API, which deleting the webhooks (which is in another part of the interface on Patreon)! It was not until you said that the webhooks are required that the penny dropped and I started looking for it as I never rely on webhooks in my own implementations of oauth, I just see them as something to speed the flow up.
