### ISSUE TITLE
Bug: Logging in with Patreon creator account evicts the tokens

### ISSUE THREAD

**Issue by mpj** [discourse/discourse-patreon#9]
I have a Discourse installation where my Admin account email is the same as the email of my Patreon creator account. Thus, when I used social login on the discourse instance to log in with my Patreon creator account, it connected that to my Discourse admin account. (I suspect that the fact that this is an admin user is irrelevant, but I'm including it for completeness sake)

Whenever I sign in this way, this re-generates the Creator's Access Token and the Creator's Refesh Token for the user, i.e. the ones listed here: https://www.patreon.com/platform/documentation/clients
This, naturally, causes the whole Patreon flow to break completely, because the access and refresh token specified in the Patreon Plugin settings are now incorrect/stale.

**Comment by xfalcox** [comment]
Hi @mpj,

This is very interesting, so you don't get a new token, they just replace the old ones? This is bad.

We have a background job that updates this tokens every 7 days, but this makes it break too.

We may need to add a new setting, that will capture the new tokens on **EVERY** login, and update the settings if the user email matches.

I'm working on something else ATM, so this may take a while.

**Comment by mpj** [comment]
@xfalcox 

> This is very interesting, so you don't get a new token, they just replace the old ones? 

I'm not exactly sure what you are asking here. I'll try to describe what happens. If I observe the "CLIENTS & API KEYS" page (https://www.patreon.com/platform/documentation/clients) and log in with my creator account (i.e. the account that owns/generated the api client) using social login on discourse, and then refresh the CLIENTS & API KEYS page, the access token and the refresh token listed on that page are now changed to new ones. Client ID and Client Secret remains intact.

**Comment by mpj** [comment]
Any news on this?

**Comment by vinothkannans** [comment]
https://github.com/discourse/discourse-patreon/pull/20
